package semgrepbundle

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"

	roomv1 "github.com/haasonsaas/room/gen/go/room/v1"
	"go.yaml.in/yaml/v3"
)

const warning = "# Code generated by semgrep-rule-bundler; DO NOT EDIT.\n"

type rule struct {
	id   string
	node *yaml.Node
}

// Bundle recursively reads rule fragments and returns a canonical document.
func Bundle(root string) ([]byte, error) {
	var paths []string
	err := filepath.WalkDir(root, func(path string, entry fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if path == root {
			if entry.Type()&os.ModeSymlink != 0 || !entry.IsDir() {
				return fmt.Errorf("fragment root is not a directory")
			}
			return nil
		}
		if entry.Type()&os.ModeSymlink != 0 {
			return fmt.Errorf("fragment entry %q is a symlink", path)
		}
		if entry.IsDir() {
			return nil
		}
		if !entry.Type().IsRegular() {
			return fmt.Errorf("fragment entry %q is not regular", path)
		}
		ext := strings.ToLower(filepath.Ext(path))
		if ext == ".yml" || ext == ".yaml" {
			paths = append(paths, path)
		}
		return nil
	})
	if err != nil {
		return nil, err
	}
	return BundleFiles(paths)
}

// BundleFiles bundles the given fragments. It is exposed to test ordering.
func BundleFiles(paths []string) ([]byte, error) {
	var rules []rule
	seen := make(map[string]string)
	for _, path := range paths {
		parsed, err := parse(path)
		if err != nil {
			return nil, err
		}
		for _, current := range parsed {
			if previous, ok := seen[current.id]; ok {
				return nil, fmt.Errorf("duplicate rule id %q in %s and %s", current.id, previous, path)
			}
			seen[current.id] = path
			rules = append(rules, current)
		}
	}
	if len(rules) == 0 {
		return nil, errors.New("no Semgrep rules found")
	}
	sort.Slice(rules, func(i, j int) bool { return rules[i].id < rules[j].id })
	sequence := &yaml.Node{Kind: yaml.SequenceNode, Tag: "!!seq"}
	for _, current := range rules {
		sequence.Content = append(sequence.Content, current.node)
	}
	document := &yaml.Node{Kind: yaml.DocumentNode, Content: []*yaml.Node{{Kind: yaml.MappingNode, Tag: "!!map", Content: []*yaml.Node{{Kind: yaml.ScalarNode, Tag: "!!str", Value: "rules"}, sequence}}}}
	var out bytes.Buffer
	out.WriteString(warning)
	encoder := yaml.NewEncoder(&out)
	encoder.SetIndent(2)
	if err := encoder.Encode(document); err != nil {
		return nil, err
	}
	return out.Bytes(), encoder.Close()
}

func parse(path string) ([]rule, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	if len(bytes.TrimSpace(data)) == 0 {
		return nil, fmt.Errorf("%s: empty fragment", path)
	}
	decoder := yaml.NewDecoder(bytes.NewReader(data))
	var document yaml.Node
	if err := decoder.Decode(&document); err != nil {
		return nil, fmt.Errorf("%s: %w", path, err)
	}
	var extra yaml.Node
	if err := decoder.Decode(&extra); !errors.Is(err, io.EOF) {
		if err == nil {
			return nil, fmt.Errorf("%s: multiple YAML documents", path)
		}
		return nil, fmt.Errorf("%s: %w", path, err)
	}
	if len(document.Content) != 1 || document.Content[0].Kind != yaml.MappingNode {
		return nil, fmt.Errorf("%s: top level must be a mapping", path)
	}
	if err := validateYAML(document.Content[0]); err != nil {
		return nil, fmt.Errorf("%s: %w", path, err)
	}
	top := document.Content[0]
	if len(top.Content) != 2 || top.Content[0].Value != "rules" || top.Content[1].Kind != yaml.SequenceNode {
		return nil, fmt.Errorf("%s: top level must contain only a rules sequence", path)
	}
	if len(top.Content[1].Content) != 1 {
		return nil, fmt.Errorf("%s: rules sequence must contain exactly one rule", path)
	}
	result := make([]rule, 0, len(top.Content[1].Content))
	for _, node := range top.Content[1].Content {
		id, err := validateRule(node)
		if err != nil {
			return nil, fmt.Errorf("%s: %w", path, err)
		}
		result = append(result, rule{id: id, node: node})
	}
	return result, nil
}

func validateRule(node *yaml.Node) (string, error) {
	if node.Kind != yaml.MappingNode {
		return "", errors.New("rule must be a mapping")
	}
	idNode := mappingValue(node, "id")
	if idNode == nil || idNode.Kind != yaml.ScalarNode || idNode.Tag != "!!str" || strings.TrimSpace(idNode.Value) == "" {
		return "", errors.New("rule id must be a non-empty scalar")
	}
	metadata := mappingValue(node, "metadata")
	if metadata == nil || metadata.Kind != yaml.MappingNode {
		return "", fmt.Errorf("rule %q has missing or invalid metadata", idNode.Value)
	}
	signal := mappingValue(metadata, "room_signal")
	if signal == nil || signal.Kind != yaml.ScalarNode || signal.Tag != "!!str" || strings.TrimSpace(signal.Value) == "" {
		return "", fmt.Errorf("rule %q has missing or invalid room_signal", idNode.Value)
	}
	value, ok := roomv1.SignalKind_value[signal.Value]
	if !ok || value == int32(roomv1.SignalKind_SIGNAL_KIND_UNSPECIFIED) {
		return "", fmt.Errorf("rule %q has unknown or unspecified room_signal %q", idNode.Value, signal.Value)
	}
	confidence := mappingValue(metadata, "room_confidence_basis_points")
	var points int
	if confidence == nil || confidence.Kind != yaml.ScalarNode || confidence.Tag != "!!int" || confidence.Decode(&points) != nil || points < 1 || points > 10000 {
		return "", fmt.Errorf("rule %q has room_confidence_basis_points outside 1..10000", idNode.Value)
	}
	return idNode.Value, nil
}

func validateYAML(node *yaml.Node) error {
	if node.Kind == yaml.AliasNode || node.Anchor != "" {
		return errors.New("anchors and aliases are not allowed")
	}
	if node.Kind == yaml.MappingNode {
		seen := make(map[string]bool, len(node.Content)/2)
		for i := 0; i+1 < len(node.Content); i += 2 {
			key := node.Content[i]
			if key.Kind != yaml.ScalarNode || key.Tag != "!!str" {
				return errors.New("mapping keys must be strings")
			}
			if key.Value == "<<" || key.Tag == "!!merge" {
				return errors.New("YAML merge keys are not allowed")
			}
			if seen[key.Value] {
				return fmt.Errorf("duplicate mapping key %q", key.Value)
			}
			seen[key.Value] = true
		}
	}
	for _, child := range node.Content {
		if err := validateYAML(child); err != nil {
			return err
		}
	}
	return nil
}

func mappingValue(node *yaml.Node, key string) *yaml.Node {
	for i := 0; i+1 < len(node.Content); i += 2 {
		if node.Content[i].Value == key {
			return node.Content[i+1]
		}
	}
	return nil
}

// WriteFile atomically updates path, leaving an identical existing file untouched.
func WriteFile(path string, data []byte) error {
	if info, err := os.Lstat(path); err == nil && info.Mode().IsRegular() {
		if current, readErr := os.ReadFile(path); readErr == nil && bytes.Equal(current, data) {
			return nil
		}
	}
	dir := filepath.Dir(path)
	temporary, err := os.CreateTemp(dir, ".room.yml-*")
	if err != nil {
		return err
	}
	name := temporary.Name()
	defer os.Remove(name)
	if _, err = temporary.Write(data); err == nil {
		err = temporary.Chmod(0o644)
	}
	if closeErr := temporary.Close(); err == nil {
		err = closeErr
	}
	if err != nil {
		return err
	}
	return os.Rename(name, path)
}
